# baseURL: https://nodejh.github.io/hugo-theme-mini
baseURL: http://localhost
languageCode: zh-tw
title: LIKO＼李璐
theme: mini
paginate: 10

hasCJKLanguage: true
permalinks:
  posts: /posts/:title/

googleAnalytics: G-GMSTCBCHEG
disqusShortname: https-mishimaliko-github-io


markup:
  highlight:
    guessSyntax: true
    style: emacs


# social:
  # github: https://github.com/nodejh
  # twitter: https://twitter.com/nodejh
  # stackoverflow: https://stackoverflow.com/users/4518882/nodejh


params:
  author: liko
  bio: Novelist
  description: Liko's Blog
  # enableRSS: true
  enableComments: false
  # enableGoogleAnalytics: true
